# Stacking and back propagation

### import data

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("iris.csv")
data = data[:100]
N = data.shape[0]

list_species=[]
for i in range(len(data.index)):
    x = data["species"][i]
    if x not in list_species:
        list_species.append(x)
data["species"] =data["species"].replace(to_replace=list_species, value=range(len(list_species)))

X = data.drop("species", 1)
y = data["species"]

## Define Z1 Linear regression

In [95]:
def linear_output_z1(x, w1, b1):
    z1 = np.dot(x, w1) + b1
    return z1

In [96]:
def sigmoid(a):
    return 1.0 / (1.0 + np.exp(-a))

In [97]:
def logistic_output_z2(x, w2, b2):
    z2 = sigmoid(np.dot(x, w2) + b2)
    return z2

In [221]:
def logistic_output(x, z1, z2, theta0, theta1, theta2, theta3):
    zf = theta0 + (z1 * theta1) + (z2 * theta2) + np.array(np.dot(x, theta3))
    return zf

In [99]:
def gradient_c_theta0(zf, y):
    gradient = sum(sigmoid(zf)-y) / N
    return gradient

In [100]:
def gradient_c_theta1(z1, zf, y):
    gradient = np.matmul(z1, (sigmoid(zf)-y)) / N
    return gradient

In [101]:
def gradient_c_theta2(z2, zf, y):
    gradient = np.matmul(z2, (sigmoid(zf)-y)) / N
    return gradient

In [125]:
def gradient_c_theta3(x, zf, y):
    gradient = np.matmul(np.transpose(x), (sigmoid(zf)-y)) / N
    return gradient

In [127]:
def gradient_c_w1(x, theta1, zf, y):
    gradient = np.matmul (np.transpose(x), theta1 * np.array((sigmoid(zf) - y))) / N
    return gradient

In [128]:
def gradient_c_b1(theta1, zf, y):
    gradient = sum(theta1 * np.array((sigmoid(zf) - y))) / N
    return gradient

In [154]:
def gradient_c_w2(x, w2, b2, theta2, zf, y):
    gradient= np.matmul(np.transpose(x), sigmoid(np.dot(x, w2) + b2) * (1 - sigmoid(np.dot(x, w2) + b2)) * (theta2 * np.array((sigmoid(zf) - y)))) / N
    return gradient

In [161]:
def gradient_c_b2(x, w2, b2, theta2, zf, y):
    gradient = sum (sigmoid(np.dot(x, w2) + b2) * (1 - sigmoid(np.dot(x, w2) + b2)) * (theta2 * np.array((sigmoid(zf) - y)))) / N
    return gradient

In [225]:
def gradient_descent(x, y, int_w1, int_w2, int_b1, int_b2, int_theta0, int_theta1, int_theta2, int_theta3, lowtrain, uptrain, iterations):
    place_w1=int_w1
    place_w2=int_w2
    place_b1=int_b1
    place_b2=int_b2
    place_theta0=int_theta0
    place_theta1=int_theta1
    place_theta2=int_theta2
    place_theta3=int_theta3
    for i in range(iterations):
        trainrate=np.random.uniform(lowtrain,uptrain,1)
        z1 = linear_output_z1(x, place_w1, place_b1)
        z2 = logistic_output_z2(x, place_w2, place_b2)
        zf = logistic_output(x, z1, z2, place_theta0, place_theta1, place_theta2, place_theta3)
        gradient_theta0 = gradient_c_theta0(zf, y)
        gradient_theta1 = gradient_c_theta1(z1, zf, y)
        gradient_theta2 = gradient_c_theta2(z2, zf, y)
        gradient_theta3 = gradient_c_theta3(x, zf, y)
        gradient_w1 = gradient_c_w1(x, int_theta1, zf, y)
        gradient_w2 = gradient_c_w2(x, int_w2, int_b2, int_theta2, zf, y)
        gradient_b1 = gradient_c_b1(int_theta1, zf, y)
        gradient_b2 = gradient_c_b2(x, int_w2, int_b2, int_theta2, zf, y)
        place_w1 = place_w1 - trainrate * gradient_w1
        place_w2 = place_w2 - trainrate * gradient_w2
        place_b1 = place_b1 - trainrate * gradient_b1
        place_b2 = place_b2 - trainrate * gradient_b2
        place_theta0 = place_theta0 - trainrate * gradient_theta0
        place_theta1 = place_theta1 - trainrate * gradient_theta1
        place_theta2 = place_theta2 - trainrate * gradient_theta2
        place_theta3 = place_theta3 - trainrate * gradient_theta3
    
    return place_w1, place_w2, place_b1, place_b2, place_theta0, place_theta1, place_theta2, place_theta3

In [238]:
int_w1, int_w2, int_b1, int_b2 = np.random.uniform(-1,1,4), np.random.uniform(-1,1,4), np.random.uniform(-1,1,1), np.random.uniform(-1,1,1)
int_theta0, int_theta1, int_theta2, int_theta3 = 1, 0, -1, np.array([1,-1,2,4])
gradient_descent(X, y, int_w1, int_w2, int_b1, int_b2, int_theta0, int_theta1, int_theta2, int_theta3, 0.01, 0.01, 1000)

(array([ 0.47891466, -0.60847597, -0.82045709,  0.12787284]),
 array([ 0.43700489,  0.59727593,  0.03817737, -0.67536054]),
 array([-0.7535505]),
 array([-0.24393357]),
 array([ 0.75751426]),
 array([ 0.34121342]),
 array([-1.23698452]),
 array([-0.17771868, -1.83192129,  1.73177632,  3.97063313]))

In [232]:
np.random.uniform(-1,1,4)

array([ 0.50008865,  0.25754575, -0.20822868,  0.06094149])